package presenter;


public enum EVENTS {

    C_DIALOG_REGISTER_PET,
    C_DIALOG_REGISTER_DOC,
    C_SCHEDULE_APPOINTMENT,
    C_SPANISH_LANGUAGE,
    C_ENGLISH_LANGUAGE,
    C_ADD_NEW_DOCTOR,
    C_ADD_NEW_PET,
    C_CANCEL,
    C_SHOW_PANEL_GRAPHICS,
    C_SHOW_PANEL_TABLES,
    C_SHOW_TABLE_MEDICINE_RARE,
    C_SHOW_LIST_OF_DOCTORS,
    C_SHOW_LIST_OF_PETS_AND_OWNER,
    C_SHOW_LIST_APPOINTMENT,
    C_BACK_IMAGE_BANNER,
    C_NEXT_IMAGE_BANNER,
    C_SHOW_HOMEPAGE,

}
